spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:/Users/soon/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
